name: Build & Upload VRChat World

on:
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:

env:
  workspace-reltive-path: "workspace"
  source-reltive-path: "source"

jobs:
  build-and-upload-nightly-world:
    runs-on: ubuntu-latest

    env:
      workspace-path: "${{ github.workspace }}/workspace"
      source-path: "${{ github.workspace }}/source"
      add-packages-script-path: "${{ github.workspace }}/source/.github/workflow-scripts/add-user-package-to-vrc-get.js"
      secret-path: "secret.json"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        if: github.event_name != 'release'
        with:
          path: ${{ env.source-path }}

      - name: Download Release Package
        uses: robinraju/release-downloader@a96f54c1b5f5e09e47d9504526e96febd949d4c2
        if: github.event_name == 'release'
        with:
          latest: true
          preRelease: false
          out-file-path: ${{ env.source-path }}
          fileName: "*.zip"
          extract: true

      - name: Download Workspace Project
        uses: robinraju/release-downloader@a96f54c1b5f5e09e47d9504526e96febd949d4c2
        with:
          repository: ${{ secrets.WORKSPACE_PROJECT_REPOSITORY }}
          tag: ${{ secrets.WORKSPACE_PROJECT_TAG }}
          out-file-path: ${{ env.workspace-path }}
          fileName: "*.zip"
          extract: true
          token: ${{ secrets.ACTION_GITHUB_TOKEN }}

      - name: Setup vrc-get
        uses: anatawa12/sh-actions/setup-vrc-get@master

      - name: Add VPM Repositories
        run: |
          vrc-get repo add https://vpm.gyoku.tech/vpm.json
          vrc-get repo add https://pkg-index.yuxiaviation.com
          vrc-get repo add https://orels1.github.io/UdonToolkit/index.json
          vrc-get repo list

      - name: Add Source Package to vrc-get
        if: github.event_name != 'release'
        run: "node ${{ env.add-packages-script-path }} ${{ env.source-path }}/src/Packages/com.yuxiaviation.v320neo.fdmi"

      - name: Add Release Pacakge to vrc-get
        if: github.event_name == 'release'
        run: "node ${{ env.add-packages-script-path }} ${{ env.source-path }}"

      - name: Resolve VPM Dependencies
        working-directory: ${{ env.workspace-path }}
        run: "vrc-get resolve"

      - name: Add Source Pacakge to Workspace
        working-directory: ${{ env.workspace-path }}
        run: "vrc-get install com.yuxiaviation.v320neo.fdmi -y"

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-Build-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-Build-

      - name: Setup Unity
        id: setup-unity
        uses: kuler90/setup-unity@cfd7f2e4c3de6577a8776104278bcb0bf541173d
        with:
          install-path: /mnt

      - name: Activate Unity
        uses: kuler90/activate-unity@0c9d33dfb862ae776357a37ba2f2ccdb9978f422
        with:
          unity-username: ${{ secrets.UNITY_EMAIL }}
          unity-password: ${{ secrets.UNITY_PASSWORD }}

      - name: Load VRChat Account Secret
        id: load-secret
        run: |
          echo ${{ secrets.VRCHAT_SECRET }} > ${{ env.secret-path }}

      - name: Build & Upload VRChat World
        run: "${{ steps.setup-unity.outputs.unity-path }} -batchmode -logFile - -executeMethod VRChatAerospaceUniversity.VRChatAutoBuild.Worlds.AutoBuildVRChatWorld.BuildAndUploadWorld"
        env:
          VRC_AUTO_BUILD_SCENE_PATH: ${{ vars.SETUP_SCENE_PATH }}
          VRC_AUTO_BUILD_USERNAME: ${{ secrets.VRCHAT_USERNAME }}
          VRC_AUTO_BUILD_PASSWORD: ${{ secrets.VRCHAT_PASSWORD }}
          VRC_AUTO_BUILD_TOTP_KEY: ${{ secrets.VRCHAT_TOTP_KEY }}
          VRC_AUTO_BUILD_SECRET_STORAGE_PATH: ${{ env.secret-path }}

      - name: Save VRChat Account Secret
        run: cat ${{ env.secret-path }} | gh secret set VRCHAT_SECRET --app actions
        env:
          GH_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
