name: Build & Upload VRChat World

on:
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:

env:
  workspace-reltive-path: "workspace"
  source-reltive-path: "source"

jobs:
  build-and-upload-nightly-world:
    runs-on: ubuntu-latest

    env:
      workspace-path: "${{ github.workspace }}/workspace"
      source-path: "${{ github.workspace }}/source"
      add-packages-script-path: "${{ github.workspace }}/source/.github/workflow-scripts/add-user-package-to-vrc-get.js"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        if: github.event_name != 'release'
        with:
          path: ${{ env.source-path }}

      - name: Download Release Package
        uses: robinraju/release-downloader@a96f54c1b5f5e09e47d9504526e96febd949d4c2
        if: github.event_name == 'release'
        with:
          latest: true
          preRelease: false
          out-file-path: ${{ env.source-path }}
          fileName: "*.zip"
          extract: true

      - name: Download Workspace Project
        uses: robinraju/release-downloader@a96f54c1b5f5e09e47d9504526e96febd949d4c2
        with:
          repository: ${{ secrets.WORKSPACE_PROJECT_REPOSITORY }}
          tag: ${{ secrets.WORKSPACE_PROJECT_TAG }}
          out-file-path: ${{ env.workspace-path }}
          fileName: "*.zip"
          extract: true
          token: ${{ secrets.WORKSPACE_PROJECT_TOKEN }}

      - name: Setup vrc-get
        uses: anatawa12/sh-actions/setup-vrc-get@master

      - name: Add VPM Repositories
        run: |
          vrc-get repo add https://vpm.gyoku.tech/vpm.json
          vrc-get repo add https://pkg-index.yuxiaviation.com
          vrc-get repo add https://orels1.github.io/UdonToolkit/index.json
          vrc-get repo list

      - name: Add Source Package to vrc-get
        if: github.event_name != 'release'
        run: "node ${{ env.add-packages-script-path }} ${{ env.source-path }}/src/Packages/com.yuxiaviation.v320neo.fdmi"

      - name: Add Release Pacakge to vrc-get
        if: github.event_name == 'release'
        run: "node ${{ env.add-packages-script-path }} ${{ env.source-path }}"

      - name: Resolve VPM Dependencies
        working-directory: ${{ env.workspace-path }}
        run: "vrc-get resolve"

      - name: Add Source Pacakge to Workspace
        working-directory: ${{ env.workspace-path }}
        run: "vrc-get install com.yuxiaviation.v320neo.fdmi -y"

      - name: Make GameCI Happy
        working-directory: ${{ env.workspace-path }}
        run: |
          git init
          echo "Make GameCI Happy" > make-gameci-happy
          git config user.email "make-gameci-happy@example.com"
          git config user.name "Make GameCI happy"
          git add make-gameci-happy
          git commit -m "Make GameCI Happy"

      - name: Build & Upload VRChat World
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          buildMethod: VRChatAerospaceUniversity.VRChatAutoBuild.Worlds.AutoBuildVRChatWorld.BuildAndUploadWorld
          projectPath: ${{ env.workspace-reltive-path }}
          versioning: None
          allowDirtyBuild: true
