name: Release

on:
  workflow_dispatch:

jobs:
  create_package:
    uses: ./.github/workflows/create-package.yml

  release:
    runs-on: ubuntu-latest
    needs: create_package
    permissions:
      contents: write
    env:
      packagePath: src/Packages/${{ vars.PACKAGE_NAME }}
    steps:
      - name: Download Package Zip Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.create_package.outputs.zipArtifact }}

      - name: Download Package UnityPackage Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.create_package.outputs.unityPackageArtifact }}

      - name: Unzip Artifacts
        run: |
          unzip ${{ needs.create_package.outputs.zipArtifact }} -d ${{ env.packagePath }}
          unzip ${{ needs.create_package.outputs.unityPackageArtifact }} -d ${{ env.packagePath }}

      # Make a release tag of the version from the package.json file
      - name: Create Tag
        id: tag_version
        uses: rickstaa/action-create-tag@a1c7777fcb2fee4f19b0f283ba888afa11678b72
        with:
          tag: "${{ needs.create_package.outputs.version }}"

      # Publish the Release to GitHub
      - name: Make Release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191
        with:
          generate_release_notes: true
          files: |
            "${{ github.workspace }}/${{ env.packagePath }}/**/*"
          tag_name: ${{ needs.create_package.outputs.version }}
