name: Setup VRChat Account

on:
  workflow_dispatch:

jobs:
  setup-vrchat-account:
    runs-on: ubuntu-latest

    env:
      secret-path: "${{ github.workspace }}/secret.json"

    steps:
      - name: Download Workspace Project
        uses: robinraju/release-downloader@a96f54c1b5f5e09e47d9504526e96febd949d4c2
        with:
          repository: ${{ secrets.WORKSPACE_PROJECT_REPOSITORY }}
          tag: ${{ secrets.SETUP_PROJECT_TAG }}
          fileName: "*.zip"
          extract: true
          token: ${{ secrets.ACTION_GITHUB_TOKEN }}

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: ${{ runner.os }}-${{ github.workflow }}-Library

      - name: Setup vrc-get
        uses: anatawa12/sh-actions/setup-vrc-get@master

      - name: Add VPM Repositories
        run: |
          vrc-get repo add https://pkg-index.yuxiaviation.com
          vrc-get repo list

      - name: Resolve VPM Dependencies
        run: "vrc-get resolve"

      - name: Add AutoBuild Pacakge to Workspace
        run: "vrc-get install com.yuxiaviation.vrchat.autobuild -y"

      - name: Install FUSE
        run: |
          sudo add-apt-repository universe
          sudo apt-get install libfuse2 -y

      - name: Setup Unity
        id: setup-unity
        uses: kuler90/setup-unity@cfd7f2e4c3de6577a8776104278bcb0bf541173d
        with:
          install-path: /mnt

      - name: Activate Unity
        uses: kuler90/activate-unity@0c9d33dfb862ae776357a37ba2f2ccdb9978f422
        with:
          unity-username: ${{ secrets.UNITY_EMAIL }}
          unity-password: ${{ secrets.UNITY_PASSWORD }}

      - name: Load VRChat Account Secret
        id: load-secret
        run: |
          echo ${{ secrets.VRCHAT_SECRET }} > ${{ env.secret-path }}

      - name: Setup VRChat Account
        run: "${{ steps.setup-unity.outputs.unity-path }} -batchmode -logFile - -executeMethod VRChatAerospaceUniversity.VRChatAutoBuild.AutoBuildAuthentication.SetupAccount"
        env:
          VRC_AUTO_BUILD_SCENE_PATH: ${{ vars.SETUP_SCENE_PATH }}
          VRC_AUTO_BUILD_USERNAME: ${{ secrets.VRCHAT_USERNAME }}
          VRC_AUTO_BUILD_PASSWORD: ${{ secrets.VRCHAT_PASSWORD }}
          VRC_AUTO_BUILD_TOTP_KEY: ${{ secrets.VRCHAT_TOTP_KEY }}
          VRC_AUTO_BUILD_SECRET_STORAGE_PATH: ${{ env.secret-path }}

      - name: Save VRChat Account Secret
        run: cat ${{ env.secret-path }} | gh secret set VRCHAT_SECRET --app actions
        env:
          GH_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
