name: Setup VRChat Account

on:
  workflow_dispatch:

jobs:
  setup-vrchat-account:
    runs-on: ubuntu-latest

    env:
      secret-path: "${{ github.workspace }}/secret.json"
      unity-docker-image: unityci/editor:ubuntu-2022.3.22f1-windows-mono-3.1.0
      get-serial-script-path: "${{ github.workspace }}/source/.github/workflow-scripts/get-serial-from-license-file.js"
      UNITY_SERIAL: XXXXX-XXXXX-XXXXX-XXXXX-XXXXX

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Workspace Project
        uses: robinraju/release-downloader@a96f54c1b5f5e09e47d9504526e96febd949d4c2
        with:
          repository: ${{ secrets.WORKSPACE_PROJECT_REPOSITORY }}
          tag: ${{ secrets.SETUP_PROJECT_TAG }}
          fileName: "*.zip"
          extract: true
          token: ${{ secrets.ACTION_GITHUB_TOKEN }}

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: ${{ runner.os }}-${{ github.workflow }}-Library

      - name: Setup vrc-get
        uses: anatawa12/sh-actions/setup-vrc-get@master

      - name: Add VPM Repositories
        run: |
          vrc-get repo add https://pkg-index.yuxiaviation.com
          vrc-get repo list

      - name: Resolve VPM Dependencies
        run: "vrc-get resolve"

      - name: Add AutoBuild Pacakge to Workspace
        run: "vrc-get install com.yuxiaviation.vrchat.autobuild -y"

      - name: Load VRChat Account Secret
        id: load-secret
        env:
          VRCHAT_SECRET: ${{ secrets.VRCHAT_SECRET }}
        run: |
          echo $VRCHAT_SECRET > ${{ env.secret-path }}

      - name: Get Unity Serial
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        run: |
          "SERIAL=`echo $UNITY_LICENSE | node ${{ env.get-serial-script-path }}`"
          "echo ::add-mask::$SERIAL"
          "echo UNITY_SERIAL=$SERIAL >> $GITHUB_ENV"

      - name: Setup VRChat Account
        run: "docker run -v ${{ github.workspace }}:/project ${{ env.unity-docker-image }} -projectPath /project -username ${{ secrets.UNITY_EMAIL }} -password ${{ secrets.UNITY_PASSWORD }} -serial ${{ env.UNITY_SERIAL }} -batchmode -logFile - -executeMethod VRChatAerospaceUniversity.VRChatAutoBuild.AutoBuildAuthentication.SetupAccount"
        env:
          VRC_AUTO_BUILD_SCENE_PATH: ${{ vars.SETUP_SCENE_PATH }}
          VRC_AUTO_BUILD_USERNAME: ${{ secrets.VRCHAT_USERNAME }}
          VRC_AUTO_BUILD_PASSWORD: ${{ secrets.VRCHAT_PASSWORD }}
          VRC_AUTO_BUILD_TOTP_KEY: ${{ secrets.VRCHAT_TOTP_KEY }}
          VRC_AUTO_BUILD_SECRET_STORAGE_PATH: ${{ env.secret-path }}

      - name: Save VRChat Account Secret
        run: cat ${{ env.secret-path }} | gh secret set VRCHAT_SECRET --app actions
        env:
          GH_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
